[2024-09-30T09:23:32.691+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: music_recommendation_system.load_and_preprocess_data scheduled__2024-09-30T09:17:11.480059+00:00 [queued]>
[2024-09-30T09:23:32.702+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: music_recommendation_system.load_and_preprocess_data scheduled__2024-09-30T09:17:11.480059+00:00 [queued]>
[2024-09-30T09:23:32.703+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-09-30T09:23:32.704+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-09-30T09:23:32.704+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-09-30T09:23:32.717+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_and_preprocess_data> on 2024-09-30 09:17:11.480059+00:00
[2024-09-30T09:23:32.726+0000] {standard_task_runner.py:55} INFO - Started process 893 to run task
[2024-09-30T09:23:32.729+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'music_recommendation_system', 'load_and_preprocess_data', 'scheduled__2024-09-30T09:17:11.480059+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/music_recommendation_retraining.py', '--cfg-path', '/tmp/tmprzym2qqb']
[2024-09-30T09:23:32.731+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask load_and_preprocess_data
[2024-09-30T09:23:32.752+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-30T09:23:32.774+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-30T09:23:32.804+0000] {task_command.py:388} INFO - Running <TaskInstance: music_recommendation_system.load_and_preprocess_data scheduled__2024-09-30T09:17:11.480059+00:00 [running]> on host 1adfe0f4f205
[2024-09-30T09:23:32.874+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=music_recommendation_system
AIRFLOW_CTX_TASK_ID=load_and_preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T09:17:11.480059+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T09:17:11.480059+00:00
[2024-09-30T09:23:32.945+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/music_recommendation_retraining.py", line 37, in load_and_preprocess_data
    df['artist_genres'] = df['artist_genres'].apply(parse_genres)
NameError: name 'parse_genres' is not defined
[2024-09-30T09:23:32.959+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=music_recommendation_system, task_id=load_and_preprocess_data, execution_date=20240930T091711, start_date=20240930T092332, end_date=20240930T092332
[2024-09-30T09:23:32.966+0000] {logging_mixin.py:137} INFO - Exception: Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1520, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1581, in _execute_task
    result = execute_callable(context=context)
  File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/***/dags/music_recommendation_retraining.py", line 37, in load_and_preprocess_data
    df['artist_genres'] = df['artist_genres'].apply(parse_genres)
NameError: name 'parse_genres' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/datahub_plugin_v22.py", line 238, in custom_on_failure_callback
    datahub_task_status_callback(context, status=InstanceRunResult.FAILURE)
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/datahub_plugin_v22.py", line 105, in datahub_task_status_callback
    DatahubGenericHook(config.datahub_conn_id).get_underlying_hook().make_emitter()
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/hooks/datahub.py", line 255, in get_underlying_hook
    conn = self.get_connection(self.datahub_conn_id)
  File "/home/***/.local/lib/python3.7/site-packages/***/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/***/.local/lib/python3.7/site-packages/***/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
***.exceptions.AirflowNotFoundException: The conn_id `datahub_rest_default` isn't defined
[2024-09-30T09:23:32.979+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task load_and_preprocess_data (name 'parse_genres' is not defined; 893)
[2024-09-30T09:23:33.023+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-09-30T09:23:33.051+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
