[2024-09-30T10:10:09.671+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: music_recommendation_system.create_user_genre_matrix scheduled__2024-09-30T10:09:02.166842+00:00 [queued]>
[2024-09-30T10:10:09.688+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: music_recommendation_system.create_user_genre_matrix scheduled__2024-09-30T10:09:02.166842+00:00 [queued]>
[2024-09-30T10:10:09.689+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-09-30T10:10:09.690+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-09-30T10:10:09.690+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-09-30T10:10:09.716+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_user_genre_matrix> on 2024-09-30 10:09:02.166842+00:00
[2024-09-30T10:10:09.729+0000] {standard_task_runner.py:55} INFO - Started process 1997 to run task
[2024-09-30T10:10:09.732+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'music_recommendation_system', 'create_user_genre_matrix', 'scheduled__2024-09-30T10:09:02.166842+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/music_recommendation_retraining.py', '--cfg-path', '/tmp/tmpishv62hu']
[2024-09-30T10:10:09.737+0000] {standard_task_runner.py:83} INFO - Job 222: Subtask create_user_genre_matrix
[2024-09-30T10:10:09.755+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-30T10:10:09.781+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-30T10:10:09.819+0000] {task_command.py:388} INFO - Running <TaskInstance: music_recommendation_system.create_user_genre_matrix scheduled__2024-09-30T10:09:02.166842+00:00 [running]> on host 1adfe0f4f205
[2024-09-30T10:10:09.922+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=music_recommendation_system
AIRFLOW_CTX_TASK_ID=create_user_genre_matrix
AIRFLOW_CTX_EXECUTION_DATE=2024-09-30T10:09:02.166842+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-30T10:09:02.166842+00:00
[2024-09-30T10:22:14.305+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-09-30T10:22:14.319+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=music_recommendation_system, task_id=create_user_genre_matrix, execution_date=20240930T100902, start_date=20240930T101009, end_date=20240930T102214
[2024-09-30T10:22:14.328+0000] {logging_mixin.py:137} INFO - Exception: Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/datahub_plugin_v22.py", line 258, in custom_on_success_callback
    datahub_task_status_callback(context, status=InstanceRunResult.SUCCESS)
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/datahub_plugin_v22.py", line 105, in datahub_task_status_callback
    DatahubGenericHook(config.datahub_conn_id).get_underlying_hook().make_emitter()
  File "/home/***/.local/lib/python3.7/site-packages/datahub_***_plugin/hooks/datahub.py", line 255, in get_underlying_hook
    conn = self.get_connection(self.datahub_conn_id)
  File "/home/***/.local/lib/python3.7/site-packages/***/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/***/.local/lib/python3.7/site-packages/***/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
***.exceptions.AirflowNotFoundException: The conn_id `datahub_rest_default` isn't defined
[2024-09-30T10:22:14.418+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-09-30T10:22:14.460+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
